src/Entity/Seasons.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SeasonsRepository")
 */
class Seasons
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $label;

    /**
     * @ORM\Column(type="date")
     */
    private $start_date;

    /**
     * @ORM\Column(type="date")
     */
    private $end_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $percent;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getPercent(): ?int
    {
        return $this->percent;
    }

    public function setPercent(int $percent): self
    {
        $this->percent = $percent;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;


use App\Entity\Bookings;
use App\Entity\Guests;
use App\Entity\Presentation;
use App\Entity\PricesPool;
use App\Entity\Rentings;
use App\Entity\RentingTypes;
use App\Entity\Seasons;
use App\Form\BookType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class HomeController extends AbstractController
{
    /**
     * @Route("/nos-locations/reserver/{id}", name="book")
     * @param RentingTypes $renting_type
     * @param Request $request
     * @return Response
     */
    public function book(RentingTypes $renting_type, Request $request): Response
    {
        $images_files = $renting_type->getMedia()->toArray()[0];

        $seasons = $this
            ->getDoctrine()
            ->getRepository(Seasons::class)
            ->findAll();

        $booking = new Bookings();

        $form = $this->createForm(BookType::class, $booking);
        $form->handleRequest($request);

        if( $form->isSubmitted() && $form->isValid() ) {
            $renting = $this
                            ->getDoctrine()
                            ->getRepository(Rentings::class)
                            ->findOneBy(['renting_type' => $renting_type->getId()]);

            $guest = new Guests();
            $guest
                ->setLastName($form->getData()->getGuest()->getLastName())
                ->setFirstName($form->getData()->getGuest()->getFirstName())
                ->setEmail($form->getData()->getGuest()->getEmail())
                ->setPhoneNumber($form->getData()->getGuest()->getPhoneNumber());
            $em = $this->getDoctrine()->getManager();
            $em->persist($guest);
            $em->flush();

            $booking
                ->setStartDate($form->getData()->getStartDate())
                ->setEndDate($form->getData()->getEndDate())
                ->setRenting($renting)
                ->setGuest($guest);

            $em = $this->getDoctrine()->getManager();
            $em->persist($booking);
            $em->flush();

            return $this->redirectToRoute('confirmBook');
        }

        return $this->render('home/book.html.twig', [
            'booking' => $booking,
            'renting_type' => $renting_type,
            'images_files' => $images_files,
            'seasons' => $seasons,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/nos-locations/confirmation-reservation", name="confirmBook")
     * @return Response
     */
    public function confirmBook(): Response
    {
        return $this->render('home/confirmBook.html.twig', [

        ]);
    }

    /**
     * @Route("/", name="home")
     */
    public function index()
    {
        $presentation = $this
                        ->getDoctrine()
                        ->getRepository(Presentation::class)
                        ->findAll();

        $image = $presentation[0]->getMedia()->toArray()[0];

        return $this->render('home/index.html.twig', [
            'presentation' => $presentation[0],
            'image' => $image
        ]);
    }

    /**
     * @Route("/nos-structures", name="structures")
     */
    public function structures()
    {
        $prices_pool = $this
                        ->getDoctrine()
                        ->getRepository(PricesPool::class)
                        ->findAll();

        $presentation = $this
            ->getDoctrine()
            ->getRepository(Presentation::class)
            ->find(1);

        $images = $presentation->getMedia()->toArray();

        return $this->render('home/structures.html.twig', [
            'prices_pool' => $prices_pool,
            'presentation' => $presentation,
            'images' => $images
        ]);
    }

    /**
     * @Route("/nos-locations", name="renting_types")
     */
    public function rentings()
    {
        $renting_types = $this
                            ->getDoctrine()
                            ->getRepository(RentingTypes::class)
                            ->findAll();

        $images_files = [];
        foreach( $renting_types as $key => $renting_type ) {
            $images_files[] = $renting_type->getMedia()->toArray()[0];
        }

        $seasons = $this
                        ->getDoctrine()
                        ->getRepository(Seasons::class)
                        ->findAll();

        return $this->render('home/renting_types.html.twig', [
            'renting_types' => $renting_types,
            'images_files' => $images_files,
            'seasons' => $seasons
        ]);
    }

    /**
     * @Route("/login", name="login")
     * @param AuthenticationUtils $authenticationUtils
     * @return Response
     */
    public function login( AuthenticationUtils $authenticationUtils ) {
        $error = $authenticationUtils->getLastAuthenticationError();
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render("home/login.html.twig", [
            'last_username' => $lastUsername,
            'error' => $error,
        ]);
    }

}

templates/home/_menu.html.twig
<nav class="navbar navbar-expand-lg navbar-light bg-secondary min-vw-100 mt-0 mb-5">
    <div class="collapse navbar-collapse pl-5">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active pl-4">
                <a class="nav-link text-light" href="{{ path( 'home' ) }}">Accueil</a>
            </li>
            <li class="nav-item active pl-4">
                <a class="nav-link text-light" href="{{ path( 'structures' ) }}">Infrastructures</a>
            </li>
            <li class="nav-item active pl-4">
                <a class="nav-link text-light" href="{{ path( 'renting_types' ) }}">Locations</a>
            </li>
        </ul>
    </div>
</nav>

templates/home/book.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="jumbotron text-center mb-0">
    <h1>Camping *** l'Espadrille Volante</h1>
</div>
<div class="row">
    {{ include('home/_menu.html.twig') }}
</div>
    <div class="container">
        <div>
            <div class="mt-5">
                <h2 class="mb-5">Réserver votre logement</h2>
            </div>
            <div class="mt-5">
                <h3 class="m-5">{{ renting_type.label }}</h3>
                <div class="text-center m-5">
                    <img src="{{ vich_uploader_asset( images_files, 'imageFileRentingTypes' ) }}" alt="">
                </div>
                <div class="m-3 mb-5">
                    {{ renting_type.description }}
                </div>
                <div class="m-3 d-flex">
                    <div class="col-6">
                        {% for season in seasons %}
                            Du {{ season.startDate|date('d/m/Y') }} au {{ season.endDate|date('d/m/Y') }} :
                            {{ renting_type.price + ( renting_type.price * season.percent / 100 ) }} € par jour ({{ season.label }})<br>
                        {% endfor %}
                    </div>
                    <div class="col-6">
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col-6">{{ form_row(form.start_date) }}</div>
                            <div class="col-6">{{ form_row(form.end_date) }}</div>
                            <div class="col-6">
                                {{ form_row(form.guest.last_name) }}
                                {{ form_row(form.guest.email) }}
                            </div>
                            <div class="col-6">
                                {{ form_row(form.guest.first_name) }}
                                {{ form_row(form.guest.phone_number) }}
                            </div>
                        </div>
                        <button class="btn btn-primary">Enregistrer</button>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home/confirmBook.html.twig
{% extends 'base.html.twig' %}

{% block body %}
<div class="jumbotron text-center mb-0">
    <h1>Camping *** l'Espadrille Volante</h1>
</div>
<div class="row">
    {{ include('home/_menu.html.twig') }}
</div>
    <div class="container">
            <div class="mt-5">
                <h2 class="mb-5">Votre réservation est confirmée !</h2>
            </div>
    </div>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron text-center mb-0">
        <h1>Camping *** l'Espadrille Volante</h1>
    </div>
    <div>
        <img src="{{ vich_uploader_asset( image, 'imageFilePresentation' ) }}" alt="notre camping" class="min-vw-100">
    </div>
    <div class="row">
        {{ include('home/_menu.html.twig') }}
    </div>

    <div class="container">
        <div class="mb-5">
            <h2 class="mb-5">{{ presentation.title }}</h2>
            <p>
                {{ presentation.description }}
            </p>
        </div>
    </div>
{% endblock %}

templates/home/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-body">
            {% if error %}
                <div class="alert alert-danger">
                    {{ error.messageKey | trans( error.messagedata, 'security' ) }}
                </div>
            {% endif %}
            <form method="POST" action="{{ path('login') }}">
                <div class="form-group">
                    <label for="username">Nom d'utilisateur</label>
                    <input id="username" name="_username" type="text" class="form-control" value="{{ last_username }}">
                </div>
                <div class="form-group">
                    <label for="password">Mot de passe</label>
                    <input id="password" name="_password" type="password" class="form-control">
                </div>
                <button type="submit" class="btn btn-primary btn-sm">
                    Connexion
                </button>
            </form>
        </div>
    </div>
{% endblock %}

templates/home/renting_types.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron text-center mb-0">
        <h1>Camping *** l'Espadrille Volante</h1>
    </div>
    <div class="row">
        {{ include('home/_menu.html.twig') }}
    </div>

    <div class="container">
        <div>
            <div class="mt-5">
                <h2 class="mb-5">Nos locations</h2>
            </div>
            {% for key, renting_type in renting_types %}
                <div class="mt-5">
                    <h3 class="m-5">{{ renting_type.label }}</h3>
                    <div class="text-center m-5">
                        <img src="{{ vich_uploader_asset( images_files[key], 'imageFileRentingTypes' ) }}" alt="">
                    </div>
                    <div class="m-3 mb-5">
                        {{ renting_type.description }}
                    </div>
                    <div class="m-3 d-flex">
                        <div class="col-8">
                            {% for season in seasons %}
                                Du {{ season.startDate|date('d/m/Y') }} au {{ season.endDate|date('d/m/Y') }} :
                                {{ renting_type.price + ( renting_type.price * season.percent / 100 ) }} € par jour ({{ season.label }})<br>
                            {% endfor %}
                        </div>
                        <div class="col-4">
                            <a href="{{ path('book', { id: renting_type.id }) }}" class="btn btn-success w-50">Réserver</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/home/structures.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="jumbotron text-center mb-0">
        <h1>Camping *** l'Espadrille Volante</h1>
    </div>
    <div class="row">
        {{ include('home/_menu.html.twig') }}
    </div>

    <div class="container">
        <div>
            <h2 class="m-5">Piscine</h2>
            <div class="mb-5 d-flex justify-content-around">
                <img src="{{ vich_uploader_asset( images[1], 'imageFilePresentation' ) }}" alt="piscine">
                <img src="{{ vich_uploader_asset( images[2], 'imageFilePresentation' ) }}" alt="piscine">
                <img src="{{ vich_uploader_asset( images[3], 'imageFilePresentation' ) }}" alt="piscine">
                <img src="{{ vich_uploader_asset( images[4], 'imageFilePresentation' ) }}" alt="piscine">
            </div>
            <p>
                {{ presentation.infoPool }}
            </p>
            <h2 class="mb-3 ml-5 mt-5">Tarifs</h2>
            <ul class="list-unstyled">
                {% for price_pool in prices_pool %}
                    <li>
                        {{ price_pool.label }} : {{ price_pool.price / 100 }} € par jour
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}